### PR TITLE
Ft signup #163553006 Sign_Up form

### PR DESCRIPTION
**Pull request by carlos-nyaga**
What does this PR do?

Creates a sign_up form for the Politico app
Description of Task to be completed?

User is able to register on the platform via a sign_up form
How should this be manually tested?

After cloning the repo go into the UI folder and open the signup.html file via a browser
Any background context you want to provide?

Contains some javascript
What are the relevant pivotal tracker stories?

#163553006

screenshot_2019-02-01_15-39-41

### CODE REVIEW

**Comment by carlos-nyaga** [comment]
#### What does this PR do?
Creates a sign_up form for the Politico app

#### Description of Task to be completed?
User is able to register on the platform via a sign_up form

#### How should this be manually tested?
After cloning the repo go into the UI folder and open the signup.html file via a browser

#### Any background context you want to provide?
Contains some javascript

#### What are the relevant pivotal tracker stories?
#163553006

**Comment by ChegeBryan** [comment]
On pr commenting...the comment should be in the PR body body it self where you have placed the screenshot.

**Comment by ChegeBryan** [comment]
You can edit the pr by placing your comment into that text box you had placed your screenshot.

**Comment by carlos-nyaga** [comment]
Will sure do.....thanks for the feedback...

**Comment by carlos-nyaga** [comment]
> You can edit the pr by placing your comment into that text box you had placed your screenshot.

Thanks again

**Pull request merged**
